import React, { createContext, useContext, useState, ReactNode } from 'react';
import { footerContent } from './FooterContent';
export type Language = 'en' | 'es' | 'fr' | 'it' | 'de' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
    dir: 'ltr' | 'rtl'; 
}

// Créer le contexte avec une valeur par défaut
const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: () => '',
  dir: 'ltr'
});

const translations: Record<Language, Record<string, string>> = {
  en: {
    //Footer
      ...footerContent.en,
    // Header
    'nav.home': 'Home',
    'nav.apps': 'Apps',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.reseller': 'Reseller',
    'nav.contact': 'Contact',
    'header.startNow': 'Start Now',
    'nav.installation': 'Installation',
    // Hero Section
    'hero.title': 'Stable, fast, and uninterrupted streaming.',
    'hero.subtitle': 'Thousands of live channels and on-demand content. Works on Smart TV, PC, and mobile. Get access in minutes.',
    'hero.startFrom': 'Start now from $15',
    'hero.whatsapp': 'Free trial',

    // Testimonials
    'testimonials.title': "Don't Trust Our Word. Trust Our Customers.",
    'testimonials.subtitle': 'Real feedback from real customers using HighStream every day',
    'testimonials.whatsapp': 'WhatsApp',
    'testimonials.read': 'Read',
    'testimonials.testimonial1': "Been using HighStream for 6 months, never had buffering issues! Perfect quality 👍",
    'testimonials.testimonial2': "Quick setup, great support team. Working perfectly on my Samsung TV 📺",
    'testimonials.testimonial3': "Finally found reliable IPTV! All channels work, no interruptions ⭐",
    'testimonials.testimonial4': "Support helped me set it up in 5 minutes. Amazing service! 🔥",
    'testimonials.testimonial5': "Best IPTV service I've tried. 4K quality is incredible 🎬",

    // Infrastructure
    'infrastructure.title': 'The Goliath Infrastructure',
    'infrastructure.servers': 'Global Servers',
    'infrastructure.backup': 'Automated Backup System',
    'infrastructure.cdn': 'Anti-Buffering CDN',
    'infrastructure.monitoring': 'Network Monitoring',
    'infrastructure.uptime': 'Uptime',
    'infrastructure.channels': 'Channels',
    'infrastructure.quality': 'Quality',
    'infrastructure.support': 'Support',

    // Pricing
    'pricing.month1': '1 Month',
    'pricing.months3': '3 Months',
    'pricing.months6': '6 Months',
    'pricing.months12': '12 Months',
    'pricing.mostPopular': 'Most Popular',
    'pricing.bestDeal': 'Best Deal',
    'pricing.subscribeNow': 'Subscribe Now',

    // Payment Methods
    'payment.title': '100% Secure & Fast Payments',
    'payment.step1': 'Buy via Eneba / Wise / Crypto',
    'payment.step2': 'Send receipt (WhatsApp / Telegram)',
    'payment.step3': 'Get access in less than 5 minutes',
    'payment.recommended': 'Eneba recommended (accepts credit & debit cards)',

    // Infrastructure content
    'infrastructure.subtitle': 'Enterprise-grade technology powering millions of streams worldwide',
    'infrastructure.globalServers': '50+ Global Servers',
    'infrastructure.globalServersDesc': 'Worldwide server network for optimal performance',
    'infrastructure.globalServersMetric': '99.9% Uptime',
    'infrastructure.backupTitle': 'Automated Backup System',
    'infrastructure.backupDesc': 'Multiple redundancies ensure continuous service',
    'infrastructure.backupMetric': 'Zero Downtime',
    'infrastructure.cdnTitle': 'Anti-Buffering CDN',
    'infrastructure.cdnDesc': 'Smart content delivery for smooth streaming',
    'infrastructure.cdnMetric': '< 1s Load Time',
    'infrastructure.monitoringTitle': '24/7 Network Monitoring',
    'infrastructure.monitoringDesc': 'Real-time monitoring and instant issue resolution',
    'infrastructure.monitoringMetric': '24/7 Support',
    'infrastructure.techTitle': 'Powered by Advanced Technology',
    'infrastructure.globalCdn': 'Global CDN',
    'infrastructure.loadBalancing': 'Load Balancing',
    'infrastructure.autoScaling': 'Auto-Scaling',
    'infrastructure.analytics': 'Real-time Analytics',

    // Payment content
    'payment.subtitle': 'Multiple payment options for your convenience and security',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'Credit & Debit Cards',
    'payment.enebaFeature1': 'Instant payment',
    'payment.enebaFeature2': 'Global acceptance',
    'payment.enebaFeature3': 'Secure checkout',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'Bank Transfer',
    'payment.wiseFeature1': 'Low fees',
    'payment.wiseFeature2': 'Multi-currency',
    'payment.wiseFeature3': 'Fast transfer',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'Cryptocurrency',
    'payment.cryptoFeature1': 'Bitcoin',
    'payment.cryptoFeature2': 'Ethereum',
    'payment.cryptoFeature3': 'Anonymous',
    'payment.howItWorks': 'How It Works',
    'payment.step1Title': 'Buy via Eneba / Wise / Crypto',
    'payment.step1Desc': 'Choose your preferred payment method',
    'payment.step2Title': 'Send receipt (WhatsApp / Telegram)',
    'payment.step2Desc': 'Forward payment confirmation to our support',
    'payment.step3Title': 'Get access in less than 5 minutes',
    'payment.step3Desc': 'Receive your login credentials instantly',
    'payment.acceptsCards': 'Accepts all major credit & debit cards worldwide',

    // Pricing content
    'pricing.title': 'Choose Your Perfect Plan',
    'pricing.subtitle': 'All plans include full access to our premium features. No hidden fees, no contracts.',
    'pricing.feature1': '20K+ Live Channels',
    'pricing.feature2': 'VOD Movies & Series',
    'pricing.feature3': '4K Ultra HD Quality',
    'pricing.feature4': 'All Device Support',
    'pricing.feature5': '24/7 Customer Support',
    'pricing.feature6': 'Anti-Buffering CDN',
    'pricing.feature7': 'Priority Support',
    'pricing.feature8': 'Multi-Device Access',
    'pricing.feature9': 'Premium Support',
    'pricing.originallyText': 'Originally',
    'pricing.paymentInfo': 'Secure payment processing • Instant activation • 24/7 support',
    'pricing.creditCards': 'Credit Cards',
    'pricing.bankTransfer': 'Bank Transfer',
    'pricing.cryptocurrency': 'Cryptocurrency',

    // Footer
    'footer.reseller': 'Want to become a reseller? Join our program.',
    'footer.margins': 'High Margins',
    'footer.fullSupport': 'Full Support',
    'footer.flexible': 'Flexible Credits',
    'footer.resellerInfo': 'Request Reseller Info',
    'footer.needHelp': 'Need help? See our FAQ',
    'footer.telegram': 'Open Telegram',
    'footer.whatsapp': 'Open WhatsApp',
    'footer.email': 'Send an Email',
    'footer.responseTime': 'Average response time: under 30 minutes',
    'footer.getSupport': 'Get Support',
    'footer.copyright': '© 2024 HighStream. All rights reserved.',
    'footer.sslSecured': 'SSL Secured',
    'footer.globalCdn': 'Global CDN',
    'footer.product': 'Product',
    'footer.company': 'Company',

    'footer.support': 'Support',
    'footer.needSupport': 'Need Support?',
    'footer.hereToHelp': "We're Here to Help",
    'footer.description': 'Premium IPTV service delivering stable, high-quality streaming to millions of users worldwide.',
    'footer.aboutUs': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    'nav.aboutUs': 'About Us',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms of Service',

    // FAQ content
    'faq.mainTitle': 'Frequently Asked Questions (FAQ)',
    'faq.intro': "Welcome to our FAQ section. We've compiled answers to the most common questions about our IPTV streaming service to give you total confidence in HighStream. Our goal is to provide you with the information you need, ensuring your experience is as seamless and secure as possible.",

    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about HighStream IPTV service',
    'faq.stillNeedHelp': 'Still need help?',
    'faq.whatsappSupport': 'WhatsApp Support',
    'faq.telegramSupport': 'Telegram Support',
        'faq.generalGettingStarted': 'General & Getting Started',
    'faq.serviceTroubleshooting': 'Service & Troubleshooting',
    'faq.accountPayments': 'Account & Payments',
    'faq.legalSecurity': 'Legal & Security',
    'faq.privacyService': 'Privacy & Our IPTV Service',

    // FAQ Questions & Answers
    'faq.whatIsIptv': 'What does IPTV mean and how does it work?',
    'faq.whatIsIptvAnswer': '**IPTV** stands for **Internet Protocol Television**. It\'s a modern technology that delivers live TV, movies, and series directly to your device through an internet connection. Instead of traditional antennas or satellite dishes, our service streams content to you via a unique **M3U link** or **Xtream Codes**, offering a more flexible and robust entertainment experience.',
    'faq.multipleDevices': 'Can I use HighStream on multiple devices?',
    'faq.multipleDevicesAnswer': 'Yes. Your subscription plan is tied to a specific number of simultaneous connections. A single account allows one connection at a time, but for plans with two or three connections, we provide a separate, independent account for each device. This ensures a stable and uninterrupted streaming experience for everyone.',
    'faq.bestApp': 'Which is the best IPTV app?',
    'faq.bestAppAnswer': 'The best app often comes down to personal preference. Our service is compatible with all major **IPTV player apps**, including **IPTV Smarters Pro**, **TiviMate**, and many others. We\'ll provide you with simple, step-by-step instructions to get started on the app of your choice.',
    'faq.willWorkTv': 'Will HighStream work with my TV?',
    'faq.willWorkTvAnswer': 'Our service works with a wide range of devices. You can easily set up HighStream on your **Smart TV** (Samsung, LG, etc.), a streaming device like a **Firestick** or **Roku**, or even a non-smart TV with a compatible media box.',
    'faq.notWorking': 'Why is my IPTV not working?',
    'faq.notWorkingAnswer': 'Most issues are simple to fix. First, check your internet speed to ensure it\'s at least **30 Mbps** for HD content. If your connection is stable, try clearing your app\'s cache or restarting your device. If the issue persists, your subscription may have expired. Our dedicated support team is here to help you troubleshoot any problem.',
    'faq.ispBlock': 'Can my internet provider block IPTV?',
    'faq.ispBlockAnswer': 'In some regions, such as the **UK** or **Spain**, certain Internet Service Providers (ISPs) may throttle or block IPTV streams. To ensure a smooth, buffer-free viewing experience, we highly recommend using a **VPN**. A VPN helps you bypass these restrictions and protects your online privacy by encrypting your internet traffic.',
    'faq.internetSpeed': 'What internet speed do I need for IPTV?',
    'faq.internetSpeedAnswer': 'We recommend a stable internet connection of at least **30 Mbps** for seamless HD streaming. A faster connection is always better for optimal performance, especially if you have multiple devices connected.',
    'faq.getService': 'How do I get my service after payment?',
    'faq.getServiceAnswer': 'After you make a one-time payment, simply send us the receipt. Our team will instantly send you your credentials (**M3U link** or **Xtream Codes**) so you can activate your service immediately.',
    'faq.whatAreXtream': 'What are Xtream Codes?',
    'faq.whatAreXtreamAnswer': '**Xtream Codes** are a convenient set of login details (username, password, and a server URL) that many IPTV player apps use. We provide these codes as an alternative to an M3U link, giving you the flexibility to choose how you access our service.',
    'faq.isLegal': 'Is IPTV legal?',
    'faq.isLegalAnswer': 'The legality of IPTV services depends on the provider. As a **legitimate service**, HighStream operates within a legal framework. We prioritize the security of our customers and do not engage in the illegal distribution of content.',
    'faq.needVpn': 'Do I need a VPN to use HighStream?',
    'faq.needVpnAnswer': 'While not mandatory, we strongly recommend a **VPN**. It\'s the most effective way to protect your online privacy and avoid potential throttling from your Internet Service Provider.',
    'faq.sharePayment': 'Does HighStream share my payment information?',
    'faq.sharePaymentAnswer': '**No**. We do not handle or store any sensitive payment information. All transactions are managed by trusted third-party processors. We only keep a record of the payment proof you provide.',
    'faq.trackViewing': 'Do you track my viewing history?',
    'faq.trackViewingAnswer': '**Absolutely not**. We do not monitor your viewing habits, the channels you watch, or any of your streaming activity. Your usage is private.',
    'faq.secureInfo': 'Is my personal information secure with HighStream?',
    'faq.secureInfoAnswer': 'Our best security measure is our **minimal data policy**. By not collecting personal data, we significantly reduce the risk of a data breach affecting your identity. The limited information we do hold is protected by standard security protocols.',
    'faq.dataProtection': 'How does HighStream\'s data protection compare to other online services?',
    'faq.dataProtectionAnswer': 'Our commitment to **minimal data collection** sets us apart. We believe this is the most effective form of online privacy available, as we don\'t hold the sensitive information that other companies might.',


    // Contact Page
    'contact.title': ' Contact an agent now',
    'contact.subtitle': 'Get instant help from our technical team',
    'contact.sendMessage': 'Send us a message',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your full name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Your message',
    'contact.send': 'Send Message',
    'contact.instantSupport': 'Instant Support',
    'contact.immediateAssistance': 'For immediate assistance, use our direct channels:',
    'contact.responseTimes': 'Response Times',
    'contact.technicalIssues': 'Technical Issues?',
    'contact.beforeContacting': 'Before contacting support, try these quick fixes:',

        // Contact additional
    'contact.minutes': 'minutes',
    'contact.hours': 'hours',
    'contact.contactForm': 'Contact Form',
    'contact.restartApp': 'Restart your IPTV app',
    'contact.checkConnection': 'Check your internet connection',
    'contact.clearCache': 'Clear app cache/data',
    'contact.tryServer': 'Try a different server location',

    // Apps Page
    'apps.title': 'Best Apps for IPTV Streaming by Device',
    'apps.subtitle': 'Choose the perfect IPTV application for your device to get the best streaming experience',
    'apps.recommended': 'Recommended',
    'apps.setupTitle': 'How to Set Up Your IPTV App',
    'apps.step1': 'Download the App',
    'apps.step1Desc': 'Install your chosen IPTV app from the official app store',
    'apps.step2': 'Get Your Credentials',
    'apps.step2Desc': 'Receive M3U URL HighStream after subscription',
    'apps.step3': 'Configure the App',
    'apps.step3Desc': 'Enter your credentials and configure player settings',
    'apps.step4': 'Start Streaming',
    'apps.step4Desc': 'Enjoy 20,000+ channels with premium quality',
    'apps.proTips': 'Pro Tips for Better Streaming',
    'apps.optimizeVideo': 'Optimize Video Quality',
    'apps.reduceBuffering': 'Reduce Buffering',
    'apps.readyToStart': 'Ready to Start Streaming?',
    'apps.readyDesc': 'Choose your subscription plan and get instant access to all IPTV apps and setup guides',
    'apps.viewPricing': 'View Pricing Plans',
    'apps.contactSupport': 'Contact Support',

        // Apps additional
    'apps.mostPopular': 'Most popular IPTV player',
    'apps.premiumExp': 'Premium IPTV experience',
    'apps.featureRich': 'Feature-rich player',
    'apps.simpleReliable': 'Simple and reliable',
    'apps.bestIos': 'Best iOS IPTV app',
    'apps.cleanInterface': 'Clean interface',
    'apps.simpleEffective': 'Simple and effective',
    'apps.multiFormat': 'Multi-format support',
    'apps.wiredConnection': 'Use wired connection when possible',
    'apps.hardwareAcceleration': 'Enable hardware acceleration',
    'apps.videoDecoder': 'Choose optimal video decoder',
    'apps.bufferSize': 'Adjust buffer size for your connection',
    'apps.closeApps': 'Close background apps',
    'apps.use5ghz': 'Use 5GHz WiFi when available',
    'apps.clearCache': 'Clear app cache regularly',
    'apps.nearestServer': 'Choose nearest server location',

    // Blog Page
    'blog.title': 'Latest Insights on IPTV Technology & Streaming Trends',
    'blog.subtitle': 'Stay updated with the latest IPTV news, tutorials, and industry insights',
    'blog.featured': 'Featured Article',
    'blog.readMore': 'Read More',
    'blog.loadMore': 'Load More Articles',
    'blog.categories.all': 'All',
    'blog.categories.technology': 'Technology',
    'blog.categories.tutorial': 'Tutorial',
    'blog.categories.comparison': 'Comparison',
    'blog.categories.legal': 'Legal',
    'blog.categories.apps': 'Apps',

    // Reseller Page
    'reseller.title': 'Become a HighStream Reseller',
    'reseller.subtitle': 'Join our profitable reseller program and start earning with premium IPTV services',
    'reseller.whyBecome': 'Why Become a Reseller?',
    'reseller.highMargins': 'High Profit Margins',
    'reseller.marginsDesc': 'Earn up to 50% commission on every sale',
    'reseller.support': '24/7 Support',
    'reseller.supportDesc': 'Dedicated reseller support team',
    'reseller.materials': 'Marketing Materials',
    'reseller.materialsDesc': 'Professional promotional content provided',
    'reseller.flexible': 'Flexible Pricing',
    'reseller.flexibleDesc': 'Set your own prices and packages',
    'reseller.packs': 'Reseller Credit Packs',
    'reseller.credits': 'Credits',
    'reseller.buyNow': 'Buy Now',
    'reseller.howItWorks': 'How It Works',
    'reseller.work1': 'Purchase Credits',
    'reseller.work1Desc': 'Buy reseller credits in bulk packages',
    'reseller.work2': 'Sell Subscriptions',
    'reseller.work2Desc': 'Use credits to activate customer accounts',
    'reseller.work3': 'Earn Profits',
    'reseller.work3Desc': 'Keep the difference as your profit margin',
    'reseller.ready': 'Ready to Start Earning?',
    'reseller.readyDesc': 'Contact our reseller team to get started with your profitable IPTV business',
    'reseller.contactUs': 'Contact Reseller Team',

       // Reseller additional
    'reseller.customerMgmt': 'Customer Management',
    'reseller.customerMgmtDesc': 'Easy dashboard to manage all your customers',
    'reseller.sell': 'Sell',
    'reseller.monthlySubscriptions': 'monthly subscriptions',
    'reseller.noExpiration': 'No expiration date',
    'reseller.technicalSupport': 'Full technical support',
    'reseller.mgmtTools': 'Customer management tools',
  },
  es: {
    // footer
      ...footerContent.es,
    // Header
    'nav.home': 'Inicio',
    'nav.apps': 'Apps',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.reseller': 'Revendedor',
    'nav.contact': 'Contacto',
    'header.startNow': 'Comenzar Ahora',

    // Hero Section
    'hero.title': 'Streaming estable, rápido e ininterrumpido.',
    'hero.subtitle': 'Miles de canales en vivo y contenido bajo demanda. Funciona en Smart TV, PC y móvil. Obtén acceso en minutos.',
    'hero.startFrom': 'Comenzar desde $15',
    'hero.whatsapp': 'Prueba gratuita',

    // Testimonials
    'testimonials.title': 'No confíes en nuestra palabra. Confía en nuestros clientes.',

    // Infrastructure
    'infrastructure.title': 'La Infraestructura Goliath',
    'infrastructure.servers': 'Servidores Globales',
    'infrastructure.backup': 'Sistema de Respaldo Automático',
    'infrastructure.cdn': 'CDN Anti-Buffering',
    'infrastructure.monitoring': 'Monitoreo de Red',
    'infrastructure.uptime': 'Tiempo Activo',
    'infrastructure.channels': 'Canales',
    'infrastructure.quality': 'Calidad',
    'infrastructure.support': 'Soporte',

    // Testimonials content
    'testimonials.subtitle': 'Comentarios reales de clientes reales usando HighStream todos los días',
    'testimonials.whatsapp': 'WhatsApp',
    'testimonials.read': 'Leído',
    'testimonials.testimonial1': "Llevo usando HighStream 6 meses, ¡nunca tuve problemas de buffering! Calidad perfecta 👍",
    'testimonials.testimonial2': "Configuración rápida, gran equipo de soporte. Funciona perfectamente en mi Samsung TV 📺",
    'testimonials.testimonial3': "¡Por fin encontré IPTV confiable! Todos los canales funcionan, sin interrupciones ⭐",
    'testimonials.testimonial4': "El soporte me ayudó a configurarlo en 5 minutos. ¡Servicio increíble! 🔥",
    'testimonials.testimonial5': "El mejor servicio IPTV que he probado. La calidad 4K es increíble 🎬",

    // Infrastructure content
    'infrastructure.subtitle': 'Tecnología de nivel empresarial potenciando millones de streams mundialmente',
    'infrastructure.globalServers': '50+ Servidores Globales',
    'infrastructure.globalServersDesc': 'Red de servidores mundial para rendimiento óptimo',
    'infrastructure.globalServersMetric': '99.9% Tiempo Activo',
    'infrastructure.backupTitle': 'Sistema de Respaldo Automático',
    'infrastructure.backupDesc': 'Múltiples redundancias aseguran servicio continuo',
    'infrastructure.backupMetric': 'Cero Tiempo Inactivo',
    'infrastructure.cdnTitle': 'CDN Anti-Buffering',
    'infrastructure.cdnDesc': 'Entrega inteligente de contenido para streaming fluido',
    'infrastructure.cdnMetric': '< 1s Tiempo de Carga',
    'infrastructure.monitoringTitle': 'Monitoreo de Red 24/7',
    'infrastructure.monitoringDesc': 'Monitoreo en tiempo real y resolución instantánea de problemas',
    'infrastructure.monitoringMetric': 'Soporte 24/7',
    'infrastructure.techTitle': 'Potenciado por Tecnología Avanzada',
    'infrastructure.globalCdn': 'CDN Global',
    'infrastructure.loadBalancing': 'Balanceo de Carga',
    'infrastructure.autoScaling': 'Auto-Escalado',
    'infrastructure.analytics': 'Analíticas en Tiempo Real',

    // Payment content
    'payment.subtitle': 'Múltiples opciones de pago para tu conveniencia y seguridad',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'Tarjetas de Crédito y Débito',
    'payment.enebaFeature1': 'Pago instantáneo',
    'payment.enebaFeature2': 'Aceptación global',
    'payment.enebaFeature3': 'Checkout seguro',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'Transferencia Bancaria',
    'payment.wiseFeature1': 'Tarifas bajas',
    'payment.wiseFeature2': 'Multi-moneda',
    'payment.wiseFeature3': 'Transferencia rápida',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'Criptomoneda',
    'payment.cryptoFeature1': 'Bitcoin',
    'payment.cryptoFeature2': 'Ethereum',
    'payment.cryptoFeature3': 'Anónimo',
    'payment.howItWorks': 'Cómo Funciona',
    'payment.step1Title': 'Comprar vía Eneba / Wise / Crypto',
    'payment.step1Desc': 'Elige tu método de pago preferido',
    'payment.step2Title': 'Enviar recibo (WhatsApp / Telegram)',
    'payment.step2Desc': 'Reenvía la confirmación de pago a nuestro soporte',
    'payment.step3Title': 'Obtener acceso en menos de 5 minutos',
    'payment.step3Desc': 'Recibe tus credenciales de acceso instantáneamente',
    'payment.acceptsCards': 'Acepta todas las principales tarjetas de crédito y débito mundialmente',

    // Pricing content
    'pricing.title': 'Elige Tu Plan Perfecto',
    'pricing.subtitle': 'Todos los planes incluyen acceso completo a nuestras características premium. Sin tarifas ocultas, sin contratos.',
    'pricing.feature1': '20K+ Canales en Vivo',
    'pricing.feature2': 'Películas y Series VOD',
    'pricing.feature3': 'Calidad 4K Ultra HD',
    'pricing.feature4': 'Soporte para Todos los Dispositivos',
    'pricing.feature5': 'Atención al Cliente 24/7',
    'pricing.feature6': 'CDN Anti-Buffering',
    'pricing.feature7': 'Soporte Prioritario',
    'pricing.feature8': 'Acceso Multi-Dispositivo',
    'pricing.feature9': 'Soporte Premium',
    'pricing.originallyText': 'Originalmente',
    'pricing.paymentInfo': 'Procesamiento de pagos seguro • Activación instantánea • Soporte 24/7',
    'pricing.creditCards': 'Tarjetas de Crédito',
    'pricing.bankTransfer': 'Transferencia Bancaria',
    'pricing.cryptocurrency': 'Criptomoneda',

    // Pricing
    'pricing.month1': '1 Mes',
    'pricing.months3': '3 Meses',
    'pricing.months6': '6 Meses',
    'pricing.months12': '12 Meses',
    'pricing.mostPopular': 'Más Popular',
    'pricing.bestDeal': 'Mejor Oferta',
    'pricing.subscribeNow': 'Suscribirse Ahora',

    // Payment Methods
    'payment.title': 'Pagos 100% Seguros y Rápidos',
    'payment.step1': 'Comprar vía Eneba / Wise / Crypto',
    'payment.step2': 'Enviar recibo (WhatsApp / Telegram)',
    'payment.step3': 'Obtener acceso en menos de 5 minutos',
    'payment.recommended': 'Eneba recomendado (acepta tarjetas de crédito y débito)',

    // Footer
    'footer.reseller': '¿Quieres ser revendedor? Únete a nuestro programa.',
    'footer.margins': 'Altos Márgenes',
    'footer.fullSupport': 'Soporte Completo',
    'footer.flexible': 'Créditos Flexibles',
    'footer.resellerInfo': 'Solicitar Info de Revendedor',
    'footer.needHelp': '¿Necesitas ayuda? Ver nuestro FAQ',
    'footer.telegram': 'Abrir Telegram',
    'footer.whatsapp': 'Abrir WhatsApp',
    'footer.email': 'Enviar un Email',
    'footer.responseTime': 'Tiempo de respuesta promedio: menos de 30 minutos',
    'footer.getSupport': 'Obtener Soporte',
    'nav.aboutUs': 'Acerca de Nosotros',
    'nav.privacy': 'Política de Privacidad',
    'nav.terms': 'Términos de Servicio',

        'footer.support': 'Soporte',
    'footer.needSupport': '¿Necesitas Soporte?',
    'footer.hereToHelp': 'Estamos Aquí para Ayudar',
    'footer.description': 'Servicio IPTV premium que ofrece streaming estable y de alta calidad a millones de usuarios en todo el mundo.',
    'footer.aboutUs': 'Acerca de Nosotros',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',

    // FAQ Page
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Encuentra respuestas a preguntas comunes sobre el servicio IPTV de HighStream',
    'faq.stillNeedHelp': '¿Aún necesitas ayuda?',
    'faq.whatsappSupport': 'Soporte WhatsApp',
    'faq.telegramSupport': 'Soporte Telegram',

    // FAQ content
    'faq.mainTitle': 'Preguntas Frecuentes (FAQ)',
    'faq.intro': 'Bienvenido a nuestra sección de FAQ. Hemos compilado respuestas a las preguntas más comunes sobre nuestro servicio de streaming IPTV para darte total confianza en HighStream. Nuestro objetivo es proporcionarte la información que necesitas, asegurando que tu experiencia sea lo más fluida y segura posible.',

        'faq.generalGettingStarted': 'General y Primeros Pasos',
    'faq.serviceTroubleshooting': 'Servicio y Solución de Problemas',
    'faq.accountPayments': 'Cuenta y Pagos',
    'faq.legalSecurity': 'Legal y Seguridad',
    'faq.privacyService': 'Privacidad y Nuestro Servicio IPTV',

    // FAQ Questions & Answers in Spanish
    'faq.whatIsIptv': '¿Qué significa IPTV y cómo funciona?',
    'faq.whatIsIptvAnswer': '**IPTV** significa **Televisión por Protocolo de Internet**. Es una tecnología moderna que entrega TV en vivo, películas y series directamente a tu dispositivo a través de una conexión a internet. En lugar de antenas tradicionales o platos satelitales, nuestro servicio transmite contenido a través de un **enlace M3U** único o **Códigos Xtream**, ofreciendo una experiencia de entretenimiento más flexible y robusta.',
    'faq.multipleDevices': '¿Puedo usar HighStream en múltiples dispositivos?',
    'faq.multipleDevicesAnswer': 'Sí. Tu plan de suscripción está vinculado a un número específico de conexiones simultáneas. Una cuenta individual permite una conexión a la vez, pero para planes con dos o tres conexiones, proporcionamos una cuenta separada e independiente para cada dispositivo. Esto asegura una experiencia de streaming estable e ininterrumpida para todos.',
    'faq.bestApp': '¿Cuál es la mejor aplicación IPTV?',
    'faq.bestAppAnswer': 'La mejor aplicación a menudo depende de la preferencia personal. Nuestro servicio es compatible con todas las principales **aplicaciones de reproductor IPTV**, incluyendo **IPTV Smarters Pro**, **TiviMate**, y muchas otras. Te proporcionaremos instrucciones simples paso a paso para comenzar en la aplicación de tu elección.',
    'faq.willWorkTv': '¿Funcionará HighStream con mi TV?',
    'faq.willWorkTvAnswer': 'Nuestro servicio funciona con una amplia gama de dispositivos. Puedes configurar fácilmente HighStream en tu **Smart TV** (Samsung, LG, etc.), un dispositivo de streaming como **Firestick** o **Roku**, o incluso un TV no inteligente con una caja multimedia compatible.',
    'faq.notWorking': '¿Por qué no funciona mi IPTV?',
    'faq.notWorkingAnswer': 'La mayoría de los problemas son simples de solucionar. Primero, verifica tu velocidad de internet para asegurar que sea al menos **30 Mbps** para contenido HD. Si tu conexión es estable, intenta limpiar la caché de tu aplicación o reiniciar tu dispositivo. Si el problema persiste, tu suscripción puede haber expirado. Nuestro equipo de soporte dedicado está aquí para ayudarte a solucionar cualquier problema.',
    'faq.ispBlock': '¿Puede mi proveedor de internet bloquear IPTV?',
    'faq.ispBlockAnswer': 'En algunas regiones, como el **Reino Unido** o **España**, ciertos Proveedores de Servicios de Internet (ISP) pueden limitar o bloquear las transmisiones IPTV. Para asegurar una experiencia de visualización fluida y sin interrupciones, recomendamos encarecidamente usar una **VPN**. Una VPN te ayuda a evitar estas restricciones y protege tu privacidad en línea encriptando tu tráfico de internet.',
    'faq.internetSpeed': '¿Qué velocidad de internet necesito para IPTV?',
    'faq.internetSpeedAnswer': 'Recomendamos una conexión a internet estable de al menos **30 Mbps** para streaming HD sin problemas. Una conexión más rápida siempre es mejor para un rendimiento óptimo, especialmente si tienes múltiples dispositivos conectados.',
    'faq.getService': '¿Cómo obtengo mi servicio después del pago?',
    'faq.getServiceAnswer': 'Después de hacer un pago único, simplemente envíanos el recibo. Nuestro equipo te enviará instantáneamente tus credenciales (**enlace M3U** o **Códigos Xtream**) para que puedas activar tu servicio inmediatamente.',
    'faq.whatAreXtream': '¿Qué son los Códigos Xtream?',
    'faq.whatAreXtreamAnswer': 'Los **Códigos Xtream** son un conjunto conveniente de detalles de inicio de sesión (nombre de usuario, contraseña y una URL del servidor) que muchas aplicaciones de reproductor IPTV utilizan. Proporcionamos estos códigos como alternativa a un enlace M3U, dándote la flexibilidad de elegir cómo acceder a nuestro servicio.',
    'faq.isLegal': '¿Es legal IPTV?',
    'faq.isLegalAnswer': 'La legalidad de los servicios IPTV depende del proveedor. Como un **servicio legítimo**, HighStream opera dentro de un marco legal. Priorizamos la seguridad de nuestros clientes y no participamos en la distribución ilegal de contenido.',
    'faq.needVpn': '¿Necesito una VPN para usar HighStream?',
    'faq.needVpnAnswer': 'Aunque no es obligatorio, recomendamos encarecidamente una **VPN**. Es la forma más efectiva de proteger tu privacidad en línea y evitar posibles limitaciones de tu Proveedor de Servicios de Internet.',
    'faq.sharePayment': '¿HighStream comparte mi información de pago?',
    'faq.sharePaymentAnswer': '**No**. No manejamos ni almacenamos información de pago sensible. Todas las transacciones son gestionadas por procesadores de terceros confiables. Solo mantenemos un registro de la prueba de pago que proporcionas.',
    'faq.trackViewing': '¿Rastrean mi historial de visualización?',
    'faq.trackViewingAnswer': '**Absolutamente no**. No monitoreamos tus hábitos de visualización, los canales que ves, o cualquier actividad de streaming. Tu uso es privado.',
    'faq.secureInfo': '¿Es segura mi información personal con HighStream?',
    'faq.secureInfoAnswer': 'Nuestra mejor medida de seguridad es nuestra **política de datos mínimos**. Al no recopilar datos personales, reducimos significativamente el riesgo de una violación de datos que afecte tu identidad. La información limitada que tenemos está protegida por protocolos de seguridad estándar.',
    'faq.dataProtection': '¿Cómo se compara la protección de datos de HighStream con otros servicios en línea?',
    'faq.dataProtectionAnswer': 'Nuestro compromiso con la **recopilación mínima de datos** nos distingue. Creemos que esta es la forma más efectiva de privacidad en línea disponible, ya que no tenemos la información sensible que otras empresas podrían tener.',




    // Contact Page
    'contact.title': 'Contacte con un agente ahora',
    'contact.subtitle': 'Obtén ayuda instantánea de nuestro equipo técnico',
    'contact.sendMessage': 'Envíanos un mensaje',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre completo',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'tu@email.com',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Tu mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.instantSupport': 'Soporte Instantáneo',
    'contact.immediateAssistance': 'Para asistencia inmediata, usa nuestros canales directos:',
    'contact.responseTimes': 'Tiempos de Respuesta',
    'contact.technicalIssues': '¿Problemas Técnicos?',
    'contact.beforeContacting': 'Antes de contactar soporte, prueba estas soluciones rápidas:',

    // Contact additional (Spanish)
    'contact.minutes': 'minutos',
    'contact.hours': 'horas',
    'contact.contactForm': 'Formulario de Contacto',
    'contact.restartApp': 'Reinicia tu app IPTV',
    'contact.checkConnection': 'Verifica tu conexión a internet',
    'contact.clearCache': 'Limpia cache/datos de la app',
    'contact.tryServer': 'Prueba una ubicación de servidor diferente',

     // Apps additional (Spanish)
    'apps.mostPopular': 'Reproductor IPTV más popular',
    'apps.premiumExp': 'Experiencia IPTV premium',
    'apps.featureRich': 'Reproductor con muchas funciones',
    'apps.simpleReliable': 'Simple y confiable',
    'apps.bestIos': 'Mejor app IPTV para iOS',
    'apps.cleanInterface': 'Interfaz limpia',
    'apps.simpleEffective': 'Simple y efectiva',
    'apps.multiFormat': 'Soporte multi-formato',
    'apps.wiredConnection': 'Usa conexión por cable cuando sea posible',
    'apps.hardwareAcceleration': 'Habilita aceleración por hardware',
    'apps.videoDecoder': 'Elige decodificador de video óptimo',
    'apps.bufferSize': 'Ajusta tamaño de buffer para tu conexión',
    'apps.closeApps': 'Cierra apps en segundo plano',
    'apps.use5ghz': 'Usa WiFi 5GHz cuando esté disponible',
    'apps.clearCache': 'Limpia cache de app regularmente',
    'apps.nearestServer': 'Elige ubicación de servidor más cercana',
    
    // Reseller additional (Spanish)
    'reseller.customerMgmt': 'Gestión de Clientes',
    'reseller.customerMgmtDesc': 'Panel fácil para gestionar todos tus clientes',
    'reseller.sell': 'Vender',
    'reseller.monthlySubscriptions': 'suscripciones mensuales',
    'reseller.noExpiration': 'Sin fecha de vencimiento',
    'reseller.technicalSupport': 'Soporte técnico completo',
    'reseller.mgmtTools': 'Herramientas de gestión de clientes',

    // Apps Page
    'apps.title': 'Mejores Apps para Streaming IPTV por Dispositivo',
    'apps.subtitle': 'Elige la aplicación IPTV perfecta para tu dispositivo para obtener la mejor experiencia de streaming',
    'apps.recommended': 'Recomendado',
    'apps.setupTitle': 'Cómo Configurar tu App IPTV',
    'apps.step1': 'Descargar la App',
    'apps.step1Desc': 'Instala tu app IPTV elegida desde la tienda oficial de apps',
    'apps.step2': 'Obtener tus Credenciales',
    'apps.step2Desc': 'Recibe URL M3U y EPG de HighStream después de la suscripción',
    'apps.step3': 'Configurar la App',
    'apps.step3Desc': 'Ingresa tus credenciales y configura los ajustes del reproductor',
    'apps.step4': 'Comenzar Streaming',
    'apps.step4Desc': 'Disfruta más de 20,000 canales con calidad premium',
    'apps.proTips': 'Consejos Pro para Mejor Streaming',
    'apps.optimizeVideo': 'Optimizar Calidad de Video',
    'apps.reduceBuffering': 'Reducir Buffering',
    'apps.readyToStart': '¿Listo para Comenzar Streaming?',
    'apps.readyDesc': 'Elige tu plan de suscripción y obtén acceso instantáneo a todas las apps IPTV y guías de configuración',
    'apps.viewPricing': 'Ver Planes de Precios',
    'apps.contactSupport': 'Contactar Soporte',

    

    // Blog Page
    'blog.title': 'Últimas Perspectivas sobre Tecnología IPTV y Tendencias de Streaming',
    'blog.subtitle': 'Mantente actualizado con las últimas noticias IPTV, tutoriales e insights de la industria',
    'blog.featured': 'Artículo Destacado',
    'blog.readMore': 'Leer Más',
    'blog.loadMore': 'Cargar Más Artículos',
    'blog.categories.all': 'Todos',
    'blog.categories.technology': 'Tecnología',
    'blog.categories.tutorial': 'Tutorial',
    'blog.categories.comparison': 'Comparación',
    'blog.categories.legal': 'Legal',
    'blog.categories.apps': 'Apps',

    // Reseller Page
    'reseller.title': 'Conviértete en Revendedor de HighStream',
    'reseller.subtitle': 'Únete a nuestro programa de revendedores rentable y comienza a ganar con servicios IPTV premium',
    'reseller.whyBecome': '¿Por qué Ser Revendedor?',
    'reseller.highMargins': 'Altos Márgenes de Ganancia',
    'reseller.marginsDesc': 'Gana hasta 50% de comisión en cada venta',
    'reseller.support': 'Soporte 24/7',
    'reseller.supportDesc': 'Equipo de soporte dedicado para revendedores',
    'reseller.materials': 'Materiales de Marketing',
    'reseller.materialsDesc': 'Contenido promocional profesional proporcionado',
    'reseller.flexible': 'Precios Flexibles',
    'reseller.flexibleDesc': 'Establece tus propios precios y paquetes',
    'reseller.packs': 'Paquetes de Créditos de Revendedor',
    'reseller.credits': 'Créditos',
    'reseller.buyNow': 'Comprar Ahora',
    'reseller.howItWorks': 'Cómo Funciona',
    'reseller.work1': 'Comprar Créditos',
    'reseller.work1Desc': 'Compra créditos de revendedor en paquetes al por mayor',
    'reseller.work2': 'Vender Suscripciones',
    'reseller.work2Desc': 'Usa créditos para activar cuentas de clientes',
    'reseller.work3': 'Ganar Ganancias',
    'reseller.work3Desc': 'Quédate con la diferencia como tu margen de ganancia',
    'reseller.ready': '¿Listo para Comenzar a Ganar?',
    'reseller.readyDesc': 'Contacta nuestro equipo de revendedores para comenzar con tu negocio IPTV rentable',
    'reseller.contactUs': 'Contactar Equipo de Revendedores',
  },
  fr: {
    // footer
    ...footerContent.fr,
    // Header
    'nav.home': 'Accueil',
    'nav.apps': 'Applications',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.reseller': 'Revendeur',
    'nav.contact': 'Contact',
    'header.startNow': 'Commencer Maintenant',

    // Hero Section
    'hero.title': 'Streaming stable, rapide et ininterrompu.',
    'hero.subtitle': 'Des milliers de chaînes en direct et de contenu à la demande. Fonctionne sur Smart TV, PC et mobile. Accès en quelques minutes.',
    'hero.startFrom': 'Commencer à partir de 15$',
    'hero.whatsapp': 'Essai gratuit',

    // Testimonials
    'testimonials.title': 'Ne nous croyez pas sur parole. Faites confiance à nos clients.',

    // Infrastructure
    'infrastructure.title': 'L\'Infrastructure Goliath',
    'infrastructure.servers': 'Serveurs Globaux',
    'infrastructure.backup': 'Système de Sauvegarde Automatique',
    'infrastructure.cdn': 'CDN Anti-Buffering',
    'infrastructure.monitoring': 'Surveillance Réseau',
    'infrastructure.uptime': 'Temps de Fonctionnement',
    'infrastructure.channels': 'Chaînes',
    'infrastructure.quality': 'Qualité',
    'infrastructure.support': 'Support',

    // Testimonials content
    'testimonials.subtitle': 'Vrais commentaires de vrais clients utilisant HighStream chaque jour',
    'testimonials.whatsapp': 'WhatsApp',
    'testimonials.read': 'Lu',
    'testimonials.testimonial1': "J'utilise HighStream depuis 6 mois, jamais eu de problèmes de mise en mémoire tampon ! Qualité parfaite 👍",
    'testimonials.testimonial2': "Configuration rapide, excellente équipe de support. Fonctionne parfaitement sur ma Samsung TV 📺",
    'testimonials.testimonial3': "Enfin trouvé une IPTV fiable ! Toutes les chaînes fonctionnent, pas d'interruptions ⭐",
    'testimonials.testimonial4': "Le support m'a aidé à le configurer en 5 minutes. Service incroyable ! 🔥",
    'testimonials.testimonial5': "Meilleur service IPTV que j'ai essayé. La qualité 4K est incroyable 🎬",

    // Infrastructure content  
    'infrastructure.subtitle': 'Technologie de niveau entreprise alimentant des millions de streams dans le monde',
    'infrastructure.globalServers': '50+ Serveurs Globaux',
    'infrastructure.globalServersDesc': 'Réseau de serveurs mondial pour performance optimale',
    'infrastructure.globalServersMetric': '99.9% Temps de Fonctionnement',
    'infrastructure.backupTitle': 'Système de Sauvegarde Automatique',
    'infrastructure.backupDesc': 'Multiples redondances assurent un service continu',
    'infrastructure.backupMetric': 'Zéro Temps d\'Arrêt',
    'infrastructure.cdnTitle': 'CDN Anti-Buffering',
    'infrastructure.cdnDesc': 'Livraison intelligente de contenu pour streaming fluide',
    'infrastructure.cdnMetric': '< 1s Temps de Chargement',
    'infrastructure.monitoringTitle': 'Surveillance Réseau 24/7',
    'infrastructure.monitoringDesc': 'Surveillance en temps réel et résolution instantanée des problèmes',
    'infrastructure.monitoringMetric': 'Support 24/7',
    'infrastructure.techTitle': 'Alimenté par Technologie Avancée',
    'infrastructure.globalCdn': 'CDN Global',
    'infrastructure.loadBalancing': 'Équilibrage de Charge',
    'infrastructure.autoScaling': 'Auto-Mise à l\'Échelle',
    'infrastructure.analytics': 'Analytiques Temps Réel',

    // Payment content
    'payment.subtitle': 'Options de paiement multiples pour votre commodité et sécurité',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'Cartes de Crédit et Débit',
    'payment.enebaFeature1': 'Paiement instantané',
    'payment.enebaFeature2': 'Acceptation mondiale',
    'payment.enebaFeature3': 'Checkout sécurisé',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'Virement Bancaire',
    'payment.wiseFeature1': 'Frais réduits',
    'payment.wiseFeature2': 'Multi-devise',
    'payment.wiseFeature3': 'Transfert rapide',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'Cryptomonnaie',
    'payment.cryptoFeature1': 'Bitcoin',
    'payment.cryptoFeature2': 'Ethereum',
    'payment.cryptoFeature3': 'Anonyme',
    'payment.howItWorks': 'Comment Ça Fonctionne',
    'payment.step1Title': 'Acheter via Eneba / Wise / Crypto',
    'payment.step1Desc': 'Choisissez votre méthode de paiement préférée',
    'payment.step2Title': 'Envoyer reçu (WhatsApp / Telegram)',
    'payment.step2Desc': 'Transférer la confirmation de paiement à notre support',
    'payment.step3Title': 'Obtenir accès en moins de 5 minutes',
    'payment.step3Desc': 'Recevez vos identifiants de connexion instantanément',
    'payment.acceptsCards': 'Accepte toutes les principales cartes de crédit et débit dans le monde',

    // Pricing content
    'pricing.title': 'Choisissez Votre Plan Parfait',
    'pricing.subtitle': 'Tous les plans incluent un accès complet à nos fonctionnalités premium. Pas de frais cachés, pas de contrats.',
    'pricing.feature1': '20K+ Chaînes en Direct',
    'pricing.feature2': 'Films et Séries VOD',
    'pricing.feature3': 'Qualité 4K Ultra HD',
    'pricing.feature4': 'Support Tous Appareils',
    'pricing.feature5': 'Support Client 24/7',
    'pricing.feature6': 'CDN Anti-Buffering',
    'pricing.feature7': 'Support Prioritaire',
    'pricing.feature8': 'Accès Multi-Appareils',
    'pricing.feature9': 'Support Premium',
    'pricing.originallyText': 'Originalement',
    'pricing.paymentInfo': 'Traitement de paiement sécurisé • Activation instantanée • Support 24/7',
    'pricing.creditCards': 'Cartes de Crédit',
    'pricing.bankTransfer': 'Virement Bancaire',
    'pricing.cryptocurrency': 'Cryptomonnaie',

    // Footer content
    'footer.copyright': '© 2024 HighStream. Tous droits réservés.',
    'footer.sslSecured': 'SSL Sécurisé',
    'footer.globalCdn': 'CDN Global',
    'footer.product': 'Produit',
    'footer.company': 'Entreprise',
    'nav.aboutUs': 'À propos de nous',
    'nav.privacy': 'Politique de Confidentialité',
    'nav.terms': 'Conditions de Service',

    // FAQ content
    'faq.mainTitle': 'Questions Fréquemment Posées (FAQ)',
    'faq.intro': 'Bienvenue dans notre section FAQ. Nous avons compilé des réponses aux questions les plus courantes sur notre service de streaming IPTV pour vous donner une confiance totale en HighStream. Notre objectif est de vous fournir les informations dont vous avez besoin, en veillant à ce que votre expérience soit aussi fluide et sécurisée que possible.',


    // Add more French translations...
    'pricing.month1': '1 Mois',
    'pricing.months3': '3 Mois',
    'pricing.months6': '6 Mois',
    'pricing.months12': '12 Mois',
    'pricing.mostPopular': 'Plus Populaire',
    'pricing.bestDeal': 'Meilleure Offre',
    'pricing.subscribeNow': 'S\'abonner Maintenant',

    // Payment Methods
    'payment.title': 'Paiements 100% Sécurisés et Rapides',
    'payment.step1': 'Acheter via Eneba / Wise / Crypto',
    'payment.step2': 'Envoyer reçu (WhatsApp / Telegram)',
    'payment.step3': 'Obtenir accès en moins de 5 minutes',
    'payment.recommended': 'Eneba recommandé (accepte cartes de crédit et débit)',

    // Footer
    'footer.reseller': 'Voulez-vous devenir revendeur ? Rejoignez notre programme.',
    'footer.margins': 'Marges Élevées',
    'footer.fullSupport': 'Support Complet',
    'footer.flexible': 'Crédits Flexibles',
    'footer.resellerInfo': 'Demander Info Revendeur',
    'footer.needHelp': 'Besoin d\'aide ? Voir notre FAQ',
    'footer.telegram': 'Ouvrir Telegram',
    'footer.whatsapp': 'Ouvrir WhatsApp',
    'footer.email': 'Envoyer un Email',
    'footer.responseTime': 'Temps de réponse moyen : moins de 30 minutes',
    'footer.getSupport': 'Obtenir Support',

    // FAQ Page
    'faq.title': 'Questions Fréquemment Posées',
    'faq.subtitle': 'Trouvez des réponses aux questions courantes sur le service IPTV HighStream',
    'faq.stillNeedHelp': 'Besoin d\'aide supplémentaire ?',
    'faq.whatsappSupport': 'Support WhatsApp',
    'faq.telegramSupport': 'Support Telegram',

    // Contact Page
    'contact.title': 'Contacter le Support',
    'contact.subtitle': 'Obtenez une aide instantanée de notre équipe technique',
    'contact.sendMessage': 'Envoyez-nous un message',
    'contact.name': 'Nom',
    'contact.namePlaceholder': 'Votre nom complet',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'votre@email.com',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Décrivez votre problème ou question...',
    'contact.send': 'Envoyer Message',
    'contact.instantSupport': 'Support Instantané',
    'contact.immediateAssistance': 'Pour une assistance immédiate, utilisez nos canaux directs :',
    'contact.responseTimes': 'Temps de Réponse',
    'contact.technicalIssues': 'Problèmes Techniques ?',
    'contact.beforeContacting': 'Avant de contacter le support, essayez ces solutions rapides :',

    // Apps Page
    'apps.title': 'Meilleures Applications pour Streaming IPTV par Appareil',
    'apps.subtitle': 'Choisissez l\'application IPTV parfaite pour votre appareil pour obtenir la meilleure expérience de streaming',
    'apps.recommended': 'Recommandé',
    'apps.setupTitle': 'Comment Configurer votre Application IPTV',
    'apps.step1': 'Télécharger l\'Application',
    'apps.step1Desc': 'Installez votre application IPTV choisie depuis le magasin d\'applications officiel',
    'apps.step2': 'Obtenir vos Identifiants',
    'apps.step2Desc': 'Recevez l\'URL M3U et EPG de HighStream après l\'abonnement',
    'apps.step3': 'Configurer l\'Application',
    'apps.step3Desc': 'Entrez vos identifiants et configurez les paramètres du lecteur',
    'apps.step4': 'Commencer le Streaming',
    'apps.step4Desc': 'Profitez de plus de 20 000 chaînes avec une qualité premium',
    'apps.proTips': 'Conseils Pro pour un Meilleur Streaming',
    'apps.optimizeVideo': 'Optimiser la Qualité Vidéo',
    'apps.reduceBuffering': 'Réduire la Mise en Mémoire Tampon',
    'apps.readyToStart': 'Prêt à Commencer le Streaming ?',
    'apps.readyDesc': 'Choisissez votre plan d\'abonnement et obtenez un accès instantané à toutes les applications IPTV et guides de configuration',
    'apps.viewPricing': 'Voir les Plans de Prix',
    'apps.contactSupport': 'Contacter le Support',

    // Blog Page
    'blog.title': 'Dernières Perspectives sur la Technologie IPTV et les Tendances de Streaming',
    'blog.subtitle': 'Restez à jour avec les dernières nouvelles IPTV, tutoriels et insights de l\'industrie',
    'blog.featured': 'Article en Vedette',
    'blog.readMore': 'Lire Plus',
    'blog.loadMore': 'Charger Plus d\'Articles',
    'blog.categories.all': 'Tous',
    'blog.categories.technology': 'Technologie',
    'blog.categories.tutorial': 'Tutoriel',
    'blog.categories.comparison': 'Comparaison',
    'blog.categories.legal': 'Légal',
    'blog.categories.apps': 'Applications',

    // Reseller Page
    'reseller.title': 'Devenez Revendeur HighStream',
    'reseller.subtitle': 'Rejoignez notre programme de revendeurs rentable et commencez à gagner avec les services IPTV premium',
    'reseller.whyBecome': 'Pourquoi Devenir Revendeur ?',
    'reseller.highMargins': 'Marges de Profit Élevées',
    'reseller.marginsDesc': 'Gagnez jusqu\'à 50% de commission sur chaque vente',
    'reseller.support': 'Support 24/7',
    'reseller.supportDesc': 'Équipe de support dédiée aux revendeurs',
    'reseller.materials': 'Matériaux de Marketing',
    'reseller.materialsDesc': 'Contenu promotionnel professionnel fourni',
    'reseller.flexible': 'Prix Flexibles',
    'reseller.flexibleDesc': 'Définissez vos propres prix et forfaits',
    'reseller.packs': 'Packs de Crédits Revendeur',
    'reseller.credits': 'Crédits',
    'reseller.buyNow': 'Acheter Maintenant',
    'reseller.howItWorks': 'Comment Ça Fonctionne',
    'reseller.work1': 'Acheter des Crédits',
    'reseller.work1Desc': 'Achetez des crédits revendeur en packs en gros',
    'reseller.work2': 'Vendre des Abonnements',
    'reseller.work2Desc': 'Utilisez les crédits pour activer les comptes clients',
    'reseller.work3': 'Gagner des Profits',
    'reseller.work3Desc': 'Gardez la différence comme votre marge de profit',
    'reseller.ready': 'Prêt à Commencer à Gagner ?',
    'reseller.readyDesc': 'Contactez notre équipe de revendeurs pour commencer votre activité IPTV rentable',
    'reseller.contactUs': 'Contacter l\'Équipe Revendeurs',
  },
  it: {
    // footer
    ...footerContent.it,
    // Header
    'nav.home': 'Home',
    'nav.apps': 'App',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.reseller': 'Rivenditore',
    'nav.contact': 'Contatto',
    'header.startNow': 'Inizia Ora',

    // Hero Section
    'hero.title': 'Streaming stabile, veloce e ininterrotto.',
    'hero.subtitle': 'Migliaia di canali live e contenuti on-demand. Funziona su Smart TV, PC e mobile. Accesso in pochi minuti.',
    'hero.startFrom': 'Inizia da $15',
    'hero.whatsapp': 'Prova gratuita',

    // Add more Italian translations...

    // Testimonials content
    'testimonials.title': 'Non fidarti delle nostre parole. Fidati dei nostri clienti.',
    'testimonials.subtitle': 'Feedback reali da clienti reali che usano HighStream ogni giorno',
    'testimonials.whatsapp': 'WhatsApp',
    'testimonials.read': 'Letto',
    'testimonials.testimonial1': "Uso HighStream da 6 mesi, mai avuto problemi di buffering! Qualità perfetta 👍",
    'testimonials.testimonial2': "Configurazione veloce, ottimo team di supporto. Funziona perfettamente sulla mia Samsung TV 📺",
    'testimonials.testimonial3': "Finalmente trovato IPTV affidabile! Tutti i canali funzionano, nessuna interruzione ⭐",
    'testimonials.testimonial4': "Il supporto mi ha aiutato a configurarlo in 5 minuti. Servizio incredibile! 🔥",
    'testimonials.testimonial5': "Miglior servizio IPTV che abbia mai provato. La qualità 4K è incredibile 🎬",

    // Infrastructure content
    'infrastructure.subtitle': 'Tecnologia di livello aziendale che alimenta milioni di stream nel mondo',
    'infrastructure.globalServers': '50+ Server Globali',
    'infrastructure.globalServersDesc': 'Rete di server mondiale per prestazioni ottimali',
    'infrastructure.globalServersMetric': '99.9% Tempo di Attività',
    'infrastructure.backupTitle': 'Sistema di Backup Automatico',
    'infrastructure.backupDesc': 'Ridondanze multiple assicurano servizio continuo',
    'infrastructure.backupMetric': 'Zero Tempo di Inattività',
    'infrastructure.cdnTitle': 'CDN Anti-Buffering',
    'infrastructure.cdnDesc': 'Consegna intelligente di contenuti per streaming fluido',
    'infrastructure.cdnMetric': '< 1s Tempo di Caricamento',
    'infrastructure.monitoringTitle': 'Monitoraggio Rete 24/7',
    'infrastructure.monitoringDesc': 'Monitoraggio in tempo reale e risoluzione istantanea dei problemi',
    'infrastructure.monitoringMetric': 'Supporto 24/7',
    'infrastructure.techTitle': 'Alimentato da Tecnologia Avanzata',
    'infrastructure.globalCdn': 'CDN Globale',
    'infrastructure.loadBalancing': 'Bilanciamento del Carico',
    'infrastructure.autoScaling': 'Auto-Scaling',
    'infrastructure.analytics': 'Analitiche in Tempo Reale',

    // Payment content
    'payment.subtitle': 'Opzioni di pagamento multiple per la tua comodità e sicurezza',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'Carte di Credito e Debito',
    'payment.enebaFeature1': 'Pagamento istantaneo',
    'payment.enebaFeature2': 'Accettazione globale',
    'payment.enebaFeature3': 'Checkout sicuro',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'Bonifico Bancario',
    'payment.wiseFeature1': 'Commissioni basse',
    'payment.wiseFeature2': 'Multi-valuta',
    'payment.wiseFeature3': 'Trasferimento veloce',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'Criptovaluta',
    'payment.cryptoFeature1': 'Bitcoin',
    'payment.cryptoFeature2': 'Ethereum',
    'payment.cryptoFeature3': 'Anonimo',
    'payment.howItWorks': 'Come Funziona',
    'payment.step1Title': 'Acquista tramite Eneba / Wise / Crypto',
    'payment.step1Desc': 'Scegli il tuo metodo di pagamento preferito',
    'payment.step2Title': 'Invia ricevuta (WhatsApp / Telegram)',
    'payment.step2Desc': 'Inoltra la conferma di pagamento al nostro supporto',
    'payment.step3Title': 'Ottieni accesso in meno di 5 minuti',
    'payment.step3Desc': 'Ricevi le tue credenziali di accesso istantaneamente',
    'payment.acceptsCards': 'Accetta tutte le principali carte di credito e debito a livello mondiale',

    // Pricing content
    'pricing.title': 'Scegli il Tuo Piano Perfetto',
    'pricing.subtitle': 'Tutti i piani includono accesso completo alle nostre funzionalità premium. Nessuna tariffa nascosta, nessun contratto.',
    'pricing.feature1': '20K+ Canali Live',
    'pricing.feature2': 'Film e Serie VOD',
    'pricing.feature3': 'Qualità 4K Ultra HD',
    'pricing.feature4': 'Supporto Tutti i Dispositivi',
    'pricing.feature5': 'Assistenza Clienti 24/7',
    'pricing.feature6': 'CDN Anti-Buffering',
    'pricing.feature7': 'Supporto Prioritario',
    'pricing.feature8': 'Accesso Multi-Dispositivo',
    'pricing.feature9': 'Supporto Premium',
    'pricing.originallyText': 'Originariamente',
    'pricing.paymentInfo': 'Elaborazione pagamenti sicura • Attivazione istantanea • Supporto 24/7',
    'pricing.creditCards': 'Carte di Credito',
    'pricing.bankTransfer': 'Bonifico Bancario',
    'pricing.cryptocurrency': 'Criptovaluta',

    // Footer content
    'footer.copyright': '© 2024 HighStream. Tutti i diritti riservati.',
    'footer.sslSecured': 'SSL Protetto',
    'footer.globalCdn': 'CDN Globale',
    'footer.product': 'Prodotto',
    'footer.company': 'Azienda',
    'nav.aboutUs': 'Chi Siamo',
    'nav.privacy': 'Politica di Riservatezza',
    'nav.terms': 'Termini di Servizio',

    // FAQ content
    'faq.mainTitle': 'Domande Frequenti (FAQ)',
    'faq.intro': 'Benvenuto nella nostra sezione FAQ. Abbiamo compilato risposte alle domande più comuni sul nostro servizio di streaming IPTV per darti totale fiducia in HighStream. Il nostro obiettivo è fornirti le informazioni di cui hai bisogno, assicurando che la tua esperienza sia il più fluida e sicura possibile.',

    // Infrastructure
    'infrastructure.title': 'L\'Infrastruttura Goliath',
    'infrastructure.servers': 'Server Globali',
    'infrastructure.backup': 'Sistema di Backup Automatico',
    'infrastructure.cdn': 'CDN Anti-Buffering',
    'infrastructure.monitoring': 'Monitoraggio Rete',
    'infrastructure.uptime': 'Tempo di Attività',
    'infrastructure.channels': 'Canali',
    'infrastructure.quality': 'Qualità',
    'infrastructure.support': 'Supporto',

    // Pricing
    'pricing.month1': '1 Mese',
    'pricing.months3': '3 Mesi',
    'pricing.months6': '6 Mesi',
    'pricing.months12': '12 Mesi',
    'pricing.mostPopular': 'Più Popolare',
    'pricing.bestDeal': 'Miglior Offerta',
    'pricing.subscribeNow': 'Iscriviti Ora',

    // Payment Methods
    'payment.title': 'Pagamenti 100% Sicuri e Veloci',
    'payment.step1': 'Acquista tramite Eneba / Wise / Crypto',
    'payment.step2': 'Invia ricevuta (WhatsApp / Telegram)',
    'payment.step3': 'Ottieni accesso in meno di 5 minuti',
    'payment.recommended': 'Eneba raccomandato (accetta carte di credito e debito)',

    // Footer
    'footer.reseller': 'Vuoi diventare rivenditore? Unisciti al nostro programma.',
    'footer.margins': 'Margini Elevati',
    'footer.fullSupport': 'Supporto Completo',
    'footer.flexible': 'Crediti Flessibili',
    'footer.resellerInfo': 'Richiedi Info Rivenditore',
    'footer.needHelp': 'Hai bisogno di aiuto? Vedi le nostre FAQ',
    'footer.telegram': 'Apri Telegram',
    'footer.whatsapp': 'Apri WhatsApp',
    'footer.email': 'Invia un Email',
    'footer.responseTime': 'Tempo di risposta medio: meno di 30 minuti',
    'footer.getSupport': 'Ottieni Supporto',

    // FAQ Page
    'faq.title': 'Domande Frequenti',
    'faq.subtitle': 'Trova risposte alle domande comuni sul servizio IPTV HighStream',
    'faq.stillNeedHelp': 'Hai ancora bisogno di aiuto?',
    'faq.whatsappSupport': 'Supporto WhatsApp',
    'faq.telegramSupport': 'Supporto Telegram',

    // Contact Page
    'contact.title': 'Contatta il Supporto',
    'contact.subtitle': 'Ottieni aiuto istantaneo dal nostro team tecnico',
    'contact.sendMessage': 'Inviaci un messaggio',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Il tuo nome completo',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'tua@email.com',
    'contact.message': 'Messaggio',
    'contact.messagePlaceholder': 'Descrivi il tuo problema o domanda...',
    'contact.send': 'Invia Messaggio',
    'contact.instantSupport': 'Supporto Istantaneo',
    'contact.immediateAssistance': 'Per assistenza immediata, usa i nostri canali diretti:',
    'contact.responseTimes': 'Tempi di Risposta',
    'contact.technicalIssues': 'Problemi Tecnici?',
    'contact.beforeContacting': 'Prima di contattare il supporto, prova queste soluzioni rapide:',

    // Apps Page
    'apps.title': 'Migliori App per Streaming IPTV per Dispositivo',
    'apps.subtitle': 'Scegli l\'applicazione IPTV perfetta per il tuo dispositivo per ottenere la migliore esperienza di streaming',
    'apps.recommended': 'Raccomandato',
    'apps.setupTitle': 'Come Configurare la tua App IPTV',
    'apps.step1': 'Scarica l\'App',
    'apps.step1Desc': 'Installa la tua app IPTV scelta dal negozio ufficiale delle app',
    'apps.step2': 'Ottieni le tue Credenziali',
    'apps.step2Desc': 'Ricevi URL M3U ed EPG da HighStream dopo la sottoscrizione',
    'apps.step3': 'Configura l\'App',
    'apps.step3Desc': 'Inserisci le tue credenziali e configura le impostazioni del lettore',
    'apps.step4': 'Inizia lo Streaming',
    'apps.step4Desc': 'Goditi oltre 20.000 canali con qualità premium',
    'apps.proTips': 'Consigli Pro per un Migliore Streaming',
    'apps.optimizeVideo': 'Ottimizza Qualità Video',
    'apps.reduceBuffering': 'Riduci Buffering',
    'apps.readyToStart': 'Pronto per Iniziare lo Streaming?',
    'apps.readyDesc': 'Scegli il tuo piano di abbonamento e ottieni accesso istantaneo a tutte le app IPTV e guide di configurazione',
    'apps.viewPricing': 'Visualizza Piani Prezzi',
    'apps.contactSupport': 'Contatta Supporto',

    // Blog Page
    'blog.title': 'Ultime Prospettive sulla Tecnologia IPTV e Tendenze di Streaming',
    'blog.subtitle': 'Rimani aggiornato con le ultime notizie IPTV, tutorial e insight del settore',
    'blog.featured': 'Articolo in Evidenza',
    'blog.readMore': 'Leggi di Più',
    'blog.loadMore': 'Carica Altri Articoli',
    'blog.categories.all': 'Tutti',
    'blog.categories.technology': 'Tecnologia',
    'blog.categories.tutorial': 'Tutorial',
    'blog.categories.comparison': 'Confronto',
    'blog.categories.legal': 'Legale',
    'blog.categories.apps': 'Applicazioni',

    // Reseller Page
    'reseller.title': 'Diventa Rivenditore HighStream',
    'reseller.subtitle': 'Unisciti al nostro programma rivenditori redditizio e inizia a guadagnare con i servizi IPTV premium',
    'reseller.whyBecome': 'Perché Diventare Rivenditore?',
    'reseller.highMargins': 'Margini di Profitto Elevati',
    'reseller.marginsDesc': 'Guadagna fino al 50% di commissione su ogni vendita',
    'reseller.support': 'Supporto 24/7',
    'reseller.supportDesc': 'Team di supporto dedicato per rivenditori',
    'reseller.materials': 'Materiali di Marketing',
    'reseller.materialsDesc': 'Contenuto promozionale professionale fornito',
    'reseller.flexible': 'Prezzi Flessibili',
    'reseller.flexibleDesc': 'Imposta i tuoi prezzi e pacchetti',
    'reseller.packs': 'Pacchetti Crediti Rivenditore',
    'reseller.credits': 'Crediti',
    'reseller.buyNow': 'Acquista Ora',
    'reseller.howItWorks': 'Come Funziona',
    'reseller.work1': 'Acquista Crediti',
    'reseller.work1Desc': 'Acquista crediti rivenditore in pacchetti all\'ingrosso',
    'reseller.work2': 'Vendi Abbonamenti',
    'reseller.work2Desc': 'Usa i crediti per attivare account clienti',
    'reseller.work3': 'Guadagna Profitti',
    'reseller.work3Desc': 'Tieni la differenza come tuo margine di profitto',
    'reseller.ready': 'Pronto per Iniziare a Guadagnare?',
    'reseller.readyDesc': 'Contatta il nostro team rivenditori per iniziare la tua attività IPTV redditizia',
    'reseller.contactUs': 'Contatta Team Rivenditori',

  },
  de: {
    // footer
    ...footerContent.de,
    // Header
    'nav.home': 'Startseite',
    'nav.apps': 'Anwendungen',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.reseller': 'Wiederverkäufer',
    'nav.contact': 'Kontakt',
    'header.startNow': 'Jetzt Starten',

    // Hero Section
    'hero.title': 'Stabiles, schnelles und ununterbrochenes Streaming.',
    'hero.subtitle': 'Tausende von Live-Kanälen und On-Demand-Inhalten. Funktioniert auf Smart TV, PC und Handy. Zugang in Minuten.',
    'hero.startFrom': 'Ab $15 starten',
    'hero.whatsapp': 'Kostenlose Testversion',

    // Add more German translations...

    // Testimonials
    'testimonials.title': 'Vertrauen Sie nicht unseren Worten. Vertrauen Sie unseren Kunden.',

    // Infrastructure
    'infrastructure.title': 'Die Goliath-Infrastruktur',
    'infrastructure.servers': 'Globale Server',
    'infrastructure.backup': 'Automatisches Backup-System',
    'infrastructure.cdn': 'Anti-Buffering CDN',
    'infrastructure.monitoring': 'Netzwerk-Überwachung',
    'infrastructure.uptime': 'Betriebszeit',
    'infrastructure.channels': 'Kanäle',
    'infrastructure.quality': 'Qualität',
    'infrastructure.support': 'Support',

    // Pricing
    'pricing.month1': '1 Monat',
    'pricing.months3': '3 Monate',
    'pricing.months6': '6 Monate',
    'pricing.months12': '12 Monate',
    'pricing.mostPopular': 'Am Beliebtesten',
    'pricing.bestDeal': 'Bestes Angebot',
    'pricing.subscribeNow': 'Jetzt Abonnieren',

    // Payment Methods
    'payment.title': '100% Sichere und Schnelle Zahlungen',
    'payment.step1': 'Kaufen über Eneba / Wise / Crypto',
    'payment.step2': 'Beleg senden (WhatsApp / Telegram)',
    'payment.step3': 'Zugang in weniger als 5 Minuten erhalten',
    'payment.recommended': 'Eneba empfohlen (akzeptiert Kredit- und Debitkarten)',

    // Testimonials content
    'testimonials.subtitle': 'Echtes Feedback von echten Kunden, die HighStream täglich nutzen',
    'testimonials.whatsapp': 'WhatsApp',
    'testimonials.read': 'Gelesen',
    'testimonials.testimonial1': "Nutze HighStream seit 6 Monaten, nie Pufferprobleme gehabt! Perfekte Qualität 👍",
    'testimonials.testimonial2': "Schnelle Einrichtung, tolles Support-Team. Funktioniert perfekt auf meinem Samsung TV 📺",
    'testimonials.testimonial3': "Endlich zuverlässiges IPTV gefunden! Alle Kanäle funktionieren, keine Unterbrechungen ⭐",
    'testimonials.testimonial4': "Support half mir bei der Einrichtung in 5 Minuten. Erstaunlicher Service! 🔥",
    'testimonials.testimonial5': "Bester IPTV-Service, den ich ausprobiert habe. 4K-Qualität ist unglaublich 🎬",

    // Infrastructure content
    'infrastructure.subtitle': 'Unternehmenstaugliche Technologie, die Millionen von Streams weltweit antreibt',
    'infrastructure.globalServers': '50+ Globale Server',
    'infrastructure.globalServersDesc': 'Weltweites Servernetzwerk für optimale Leistung',
    'infrastructure.globalServersMetric': '99.9% Betriebszeit',
    'infrastructure.backupTitle': 'Automatisches Backup-System',
    'infrastructure.backupDesc': 'Mehrfache Redundanzen gewährleisten kontinuierlichen Service',
    'infrastructure.backupMetric': 'Null Ausfallzeit',
    'infrastructure.cdnTitle': 'Anti-Puffering CDN',
    'infrastructure.cdnDesc': 'Intelligente Inhaltslieferung für reibungsloses Streaming',
    'infrastructure.cdnMetric': '< 1s Ladezeit',
    'infrastructure.monitoringTitle': '24/7 Netzwerk-Überwachung',
    'infrastructure.monitoringDesc': 'Echtzeit-Überwachung und sofortige Problemlösung',
    'infrastructure.monitoringMetric': '24/7 Support',
    'infrastructure.techTitle': 'Angetrieben von Fortschrittlicher Technologie',
    'infrastructure.globalCdn': 'Globales CDN',
    'infrastructure.loadBalancing': 'Lastausgleich',
    'infrastructure.autoScaling': 'Auto-Skalierung',
    'infrastructure.analytics': 'Echtzeit-Analytics',

    // Payment content
    'payment.subtitle': 'Mehrere Zahlungsoptionen für Ihre Bequemlichkeit und Sicherheit',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'Kredit- und Debitkarten',
    'payment.enebaFeature1': 'Sofortige Zahlung',
    'payment.enebaFeature2': 'Weltweite Akzeptanz',
    'payment.enebaFeature3': 'Sicherer Checkout',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'Banküberweisung',
    'payment.wiseFeature1': 'Niedrige Gebühren',
    'payment.wiseFeature2': 'Multi-Währung',
    'payment.wiseFeature3': 'Schneller Transfer',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'Kryptowährung',
    'payment.cryptoFeature1': 'Bitcoin',
    'payment.cryptoFeature2': 'Ethereum',
    'payment.cryptoFeature3': 'Anonym',
    'payment.howItWorks': 'Wie Es Funktioniert',
    'payment.step1Title': 'Kaufen über Eneba / Wise / Crypto',
    'payment.step1Desc': 'Wählen Sie Ihre bevorzugte Zahlungsmethode',
    'payment.step2Title': 'Beleg senden (WhatsApp / Telegram)',
    'payment.step2Desc': 'Zahlungsbestätigung an unseren Support weiterleiten',
    'payment.step3Title': 'Zugang in weniger als 5 Minuten erhalten',
    'payment.step3Desc': 'Erhalten Sie Ihre Anmeldedaten sofort',
    'payment.acceptsCards': 'Akzeptiert alle wichtigen Kredit- und Debitkarten weltweit',

    // Pricing content
    'pricing.title': 'Wählen Sie Ihren Perfekten Plan',
    'pricing.subtitle': 'Alle Pläne beinhalten vollen Zugang zu unseren Premium-Features. Keine versteckten Gebühren, keine Verträge.',
    'pricing.feature1': '20K+ Live-Kanäle',
    'pricing.feature2': 'VOD Filme & Serien',
    'pricing.feature3': '4K Ultra HD Qualität',
    'pricing.feature4': 'Alle Geräte-Unterstützung',
    'pricing.feature5': '24/7 Kundensupport',
    'pricing.feature6': 'Anti-Puffering CDN',
    'pricing.feature7': 'Prioritäts-Support',
    'pricing.feature8': 'Multi-Geräte Zugang',
    'pricing.feature9': 'Premium Support',
    'pricing.originallyText': 'Ursprünglich',
    'pricing.paymentInfo': 'Sichere Zahlungsabwicklung • Sofortige Aktivierung • 24/7 Support',
    'pricing.creditCards': 'Kreditkarten',
    'pricing.bankTransfer': 'Banküberweisung',
    'pricing.cryptocurrency': 'Kryptowährung',

    // Footer content
    'footer.copyright': '© 2024 HighStream. Alle Rechte vorbehalten.',
    'footer.sslSecured': 'SSL Gesichert',
    'footer.globalCdn': 'Globales CDN',
    'footer.product': 'Produkt',
    'footer.company': 'Unternehmen',

    // FAQ content
    'faq.mainTitle': 'Häufig Gestellte Fragen (FAQ)',
    'faq.intro': 'Willkommen in unserem FAQ-Bereich. Wir haben Antworten auf die häufigsten Fragen zu unserem IPTV-Streaming-Service zusammengestellt, um Ihnen volles Vertrauen in HighStream zu geben. Unser Ziel ist es, Ihnen die Informationen zu liefern, die Sie benötigen, und sicherzustellen, dass Ihre Erfahrung so reibungslos und sicher wie möglich ist.',

    // Footer
    'footer.reseller': 'Möchten Sie Wiederverkäufer werden? Treten Sie unserem Programm bei.',
    'footer.margins': 'Hohe Margen',
    'footer.fullSupport': 'Vollständiger Support',
    'footer.flexible': 'Flexible Credits',
    'footer.resellerInfo': 'Wiederverkäufer-Info Anfordern',
    'footer.needHelp': 'Brauchen Sie Hilfe? Siehe unsere FAQ',
    'footer.telegram': 'Telegram Öffnen',
    'footer.whatsapp': 'WhatsApp Öffnen',
    'footer.email': 'E-Mail Senden',
    'footer.responseTime': 'Durchschnittliche Antwortzeit: unter 30 Minuten',
    'footer.getSupport': 'Support Erhalten',
    'nav.aboutUs': 'Über Uns',
    'nav.privacy': 'Datenschutz-Bestimmungen',
    'nav.terms': 'Nutzungsbedingungen',

    // FAQ Page
    'faq.title': 'Häufig Gestellte Fragen',
    'faq.subtitle': 'Finden Sie Antworten auf häufige Fragen zum HighStream IPTV-Service',
    'faq.stillNeedHelp': 'Brauchen Sie noch Hilfe?',
    'faq.whatsappSupport': 'WhatsApp Support',
    'faq.telegramSupport': 'Telegram Support',

    // Contact Page
    'contact.title': 'Support Kontaktieren',
    'contact.subtitle': 'Erhalten Sie sofortige Hilfe von unserem technischen Team',
    'contact.sendMessage': 'Senden Sie uns eine Nachricht',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Ihr vollständiger Name',
    'contact.email': 'E-Mail',
    'contact.emailPlaceholder': 'ihre@email.com',
    'contact.message': 'Nachricht',
    'contact.messagePlaceholder': 'Beschreiben Sie Ihr Problem oder Ihre Frage...',
    'contact.send': 'Nachricht Senden',
    'contact.instantSupport': 'Sofortiger Support',
    'contact.immediateAssistance': 'Für sofortige Hilfe nutzen Sie unsere direkten Kanäle:',
    'contact.responseTimes': 'Antwortzeiten',
    'contact.technicalIssues': 'Technische Probleme?',
    'contact.beforeContacting': 'Bevor Sie den Support kontaktieren, versuchen Sie diese schnellen Lösungen:',

    // Apps Page
    'apps.title': 'Beste Apps für IPTV-Streaming nach Gerät',
    'apps.subtitle': 'Wählen Sie die perfekte IPTV-Anwendung für Ihr Gerät, um das beste Streaming-Erlebnis zu erhalten',
    'apps.recommended': 'Empfohlen',
    'apps.setupTitle': 'So Richten Sie Ihre IPTV-App Ein',
    'apps.step1': 'App Herunterladen',
    'apps.step1Desc': 'Installieren Sie Ihre gewählte IPTV-App aus dem offiziellen App Store',
    'apps.step2': 'Ihre Zugangsdaten Erhalten',
    'apps.step2Desc': 'Erhalten Sie M3U-URL und EPG von HighStream nach dem Abonnement',
    'apps.step3': 'App Konfigurieren',
    'apps.step3Desc': 'Geben Sie Ihre Zugangsdaten ein und konfigurieren Sie die Player-Einstellungen',
    'apps.step4': 'Streaming Starten',
    'apps.step4Desc': 'Genießen Sie über 20.000 Kanäle in Premium-Qualität',
    'apps.proTips': 'Profi-Tipps für Besseres Streaming',
    'apps.optimizeVideo': 'Video-Qualität Optimieren',
    'apps.reduceBuffering': 'Pufferung Reduzieren',
    'apps.readyToStart': 'Bereit zum Streaming zu Starten?',
    'apps.readyDesc': 'Wählen Sie Ihren Abonnement-Plan und erhalten Sie sofortigen Zugang zu allen IPTV-Apps und Setup-Anleitungen',
    'apps.viewPricing': 'Preispläne Ansehen',
    'apps.contactSupport': 'Support Kontaktieren',

    // Blog Page
    'blog.title': 'Neueste Einblicke in IPTV-Technologie & Streaming-Trends',
    'blog.subtitle': 'Bleiben Sie auf dem neuesten Stand mit den neuesten IPTV-Nachrichten, Tutorials und Brancheneinblicken',
    'blog.featured': 'Hauptartikel',
    'blog.readMore': 'Mehr Lesen',
    'blog.loadMore': 'Weitere Artikel Laden',
    'blog.categories.all': 'Alle',
    'blog.categories.technology': 'Technologie',
    'blog.categories.tutorial': 'Tutorial',
    'blog.categories.comparison': 'Vergleich',
    'blog.categories.legal': 'Rechtlich',
    'blog.categories.apps': 'Anwendungen',

    // Reseller Page
    'reseller.title': 'Werden Sie HighStream Wiederverkäufer',
    'reseller.subtitle': 'Treten Sie unserem profitablen Wiederverkäufer-Programm bei und beginnen Sie mit Premium-IPTV-Services zu verdienen',
    'reseller.whyBecome': 'Warum Wiederverkäufer Werden?',
    'reseller.highMargins': 'Hohe Gewinnmargen',
    'reseller.marginsDesc': 'Verdienen Sie bis zu 50% Provision bei jedem Verkauf',
    'reseller.support': '24/7 Support',
    'reseller.supportDesc': 'Dediziertes Wiederverkäufer-Support-Team',
    'reseller.materials': 'Marketing-Materialien',
    'reseller.materialsDesc': 'Professionelle Werbeinhalte bereitgestellt',
    'reseller.flexible': 'Flexible Preise',
    'reseller.flexibleDesc': 'Setzen Sie Ihre eigenen Preise und Pakete',
    'reseller.packs': 'Wiederverkäufer Credit-Pakete',
    'reseller.credits': 'Credits',
    'reseller.buyNow': 'Jetzt Kaufen',
    'reseller.howItWorks': 'Wie Es Funktioniert',
    'reseller.work1': 'Credits Kaufen',
    'reseller.work1Desc': 'Kaufen Sie Wiederverkäufer-Credits in Großhandelspaketen',
    'reseller.work2': 'Abonnements Verkaufen',
    'reseller.work2Desc': 'Verwenden Sie Credits zur Aktivierung von Kundenkonten',
    'reseller.work3': 'Gewinne Erzielen',
    'reseller.work3Desc': 'Behalten Sie die Differenz als Ihre Gewinnmarge',
    'reseller.ready': 'Bereit Anzufangen zu Verdienen?',
    'reseller.readyDesc': 'Kontaktieren Sie unser Wiederverkäufer-Team, um mit Ihrem profitablen IPTV-Geschäft zu beginnen',
    'reseller.contactUs': 'Wiederverkäufer-Team Kontaktieren',


  },
  ar: {
    // footer
    ...footerContent.ar,
    // Header
    'nav.home': 'الرئيسية',
    'nav.apps': 'التطبيقات',
    'nav.blog': 'المدونة',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.reseller': 'موزع',
    'nav.contact': 'اتصل بنا',
    'header.startNow': 'ابدأ الآن',

    // Hero Section
    'hero.title': 'بث مستقر وسريع وغير منقطع.',
    'hero.subtitle': 'آلاف القنوات المباشرة والمحتوى عند الطلب. يعمل على التلفزيون الذكي والكمبيوتر والهاتف المحمول. احصل على الوصول في دقائق.',
    'hero.startFrom': 'ابدأ من 15 دولار',
    'hero.whatsapp': 'تجربة مجانية',

    // Add more Arabic translations...

    // Testimonials
    'testimonials.title': 'لا تثق في كلماتنا. ثق في عملائنا.',

    // Infrastructure
    'infrastructure.title': 'البنية التحتية العملاقة',
    'infrastructure.servers': 'خوادم عالمية',
    'infrastructure.backup': 'نظام النسخ الاحتياطي التلقائي',
    'infrastructure.cdn': 'شبكة CDN مضادة للتخزين المؤقت',
    'infrastructure.monitoring': 'مراقبة الشبكة',
    'infrastructure.uptime': 'وقت التشغيل',
    'infrastructure.channels': 'القنوات',
    'infrastructure.quality': 'الجودة',
    'infrastructure.support': 'الدعم',

    // Pricing
    'pricing.month1': 'شهر واحد',
    'pricing.months3': '3 أشهر',
    'pricing.months6': '6 أشهر',
    'pricing.months12': '12 شهر',
    'pricing.mostPopular': 'الأكثر شعبية',
    'pricing.bestDeal': 'أفضل صفقة',
    'pricing.subscribeNow': 'اشترك الآن',

    // Payment Methods
    'payment.title': 'مدفوعات آمنة وسريعة 100%',
    'payment.step1': 'الشراء عبر Eneba / Wise / Crypto',
    'payment.step2': 'إرسال الإيصال (واتساب / تلغرام)',
    'payment.step3': 'الحصول على الوصول في أقل من 5 دقائق',
    'payment.recommended': 'Eneba موصى به (يقبل بطاقات الائتمان والخصم)',

    // Footer
    'footer.reseller': 'هل تريد أن تصبح موزعاً؟ انضم إلى برنامجنا.',
    'footer.margins': 'هوامش عالية',
    'footer.fullSupport': 'دعم كامل',
    'footer.flexible': 'أرصدة مرنة',
    'footer.resellerInfo': 'طلب معلومات الموزع',
    'footer.needHelp': 'تحتاج مساعدة؟ انظر الأسئلة الشائعة',
    'footer.telegram': 'فتح تلغرام',
    'footer.whatsapp': 'فتح واتساب',
    'footer.email': 'إرسال بريد إلكتروني',
    'footer.responseTime': 'متوسط وقت الاستجابة: أقل من 30 دقيقة',
    'footer.getSupport': 'الحصول على الدعم',
    'nav.aboutUs': 'من نحن',
    'nav.privacy': 'سياسة الخصوصية',
    'nav.terms': 'شروط الخدمة',

    // FAQ Page
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'ابحث عن إجابات للأسئلة الشائعة حول خدمة IPTV من HighStream',
    'faq.stillNeedHelp': 'لا تزال بحاجة إلى مساعدة؟',
    'faq.whatsappSupport': 'دعم واتساب',
    'faq.telegramSupport': 'دعم تلغرام',

    // Contact Page
    'contact.title': 'اتصل بالدعم',
    'contact.subtitle': 'احصل على مساعدة فورية من فريقنا التقني',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.name': 'الاسم',
    'contact.namePlaceholder': 'اسمك الكامل',
    'contact.email': 'البريد الإلكتروني',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'اوصف مشكلتك أو سؤالك...',
    'contact.send': 'إرسال الرسالة',
    'contact.instantSupport': 'دعم فوري',
    'contact.immediateAssistance': 'للحصول على المساعدة الفورية، استخدم قنواتنا المباشرة:',
    'contact.responseTimes': 'أوقات الاستجابة',
    'contact.technicalIssues': 'مشاكل تقنية؟',
    'contact.beforeContacting': 'قبل الاتصال بالدعم، جرب هذه الحلول السريعة:',

    // Apps Page
    'apps.title': 'أفضل تطبيقات البث IPTV حسب الجهاز',
    'apps.subtitle': 'اختر تطبيق IPTV المثالي لجهازك للحصول على أفضل تجربة بث',
    'apps.recommended': 'موصى به',
    'apps.setupTitle': 'كيفية إعداد تطبيق IPTV الخاص بك',
    'apps.step1': 'تحميل التطبيق',
    'apps.step1Desc': 'قم بتثبيت تطبيق IPTV المختار من متجر التطبيقات الرسمي',
    'apps.step2': 'الحصول على بيانات الاعتماد',
    'apps.step2Desc': 'استلم رابط M3U وEPG من HighStream بعد الاشتراك',
    'apps.step3': 'تكوين التطبيق',
    'apps.step3Desc': 'أدخل بيانات الاعتماد وقم بتكوين إعدادات المشغل',
    'apps.step4': 'بدء البث',
    'apps.step4Desc': 'استمتع بأكثر من 20000 قناة بجودة ممتازة',
    'apps.proTips': 'نصائح احترافية لبث أفضل',
    'apps.optimizeVideo': 'تحسين جودة الفيديو',
    'apps.reduceBuffering': 'تقليل التخزين المؤقت',
    'apps.readyToStart': 'جاهز لبدء البث؟',
    'apps.readyDesc': 'اختر خطة الاشتراك الخاصة بك واحصل على وصول فوري لجميع تطبيقات IPTV وأدلة الإعداد',
    'apps.viewPricing': 'عرض خطط الأسعار',
    'apps.contactSupport': 'اتصل بالدعم',

    // Blog Page
    'blog.title': 'أحدث الرؤى حول تقنية IPTV واتجاهات البث',
    'blog.subtitle': 'ابق محدثاً مع أحدث أخبار IPTV والدروس ورؤى الصناعة',
    'blog.featured': 'مقال مميز',
    'blog.readMore': 'اقرأ المزيد',
    'blog.loadMore': 'تحميل المزيد من المقالات',
    'blog.categories.all': 'الكل',
    'blog.categories.technology': 'التكنولوجيا',
    'blog.categories.tutorial': 'دروس',
    'blog.categories.comparison': 'مقارنة',
    'blog.categories.legal': 'قانوني',
    'blog.categories.apps': 'التطبيقات',

    // Reseller Page
    'reseller.title': 'كن موزع HighStream',
    'reseller.subtitle': 'انضم إلى برنامج الموزعين المربح واربح مع خدمات IPTV المميزة',
    'reseller.whyBecome': 'لماذا تصبح موزعاً؟',
    'reseller.highMargins': 'هوامش ربح عالية',
    'reseller.marginsDesc': 'اربح حتى 50% عمولة على كل بيعة',
    'reseller.support': 'دعم 24/7',
    'reseller.supportDesc': 'فريق دعم مخصص للموزعين',
    'reseller.materials': 'مواد تسويقية',
    'reseller.materialsDesc': 'محتوى ترويجي احترافي مقدم',
    'reseller.flexible': 'أسعار مرنة',
    'reseller.flexibleDesc': 'حدد أسعارك وحزمك الخاصة',
    'reseller.packs': 'حزم أرصدة الموزع',
    'reseller.credits': 'الأرصدة',
    'reseller.buyNow': 'اشتر الآن',
    'reseller.howItWorks': 'كيف يعمل',
    'reseller.work1': 'شراء الأرصدة',
    'reseller.work1Desc': 'اشتر أرصدة الموزع في حزم بالجملة',
    'reseller.work2': 'بيع الاشتراكات',
    'reseller.work2Desc': 'استخدم الأرصدة لتفعيل حسابات العملاء',
    'reseller.work3': 'كسب الأرباح',
    'reseller.work3Desc': 'احتفظ بالفرق كهامش ربحك',
    'reseller.ready': 'جاهز لبدء الكسب؟',
    'reseller.readyDesc': 'اتصل بفريق الموزعين لدينا لبدء عملك المربح في IPTV',
    'reseller.contactUs': 'اتصل بفريق الموزعين',

    // Testimonials content
    'testimonials.subtitle': 'HighStream تعليقات حقيقية من عملاء حقيقيين يستخدمون  كل يوم',
    'testimonials.whatsapp': 'واتساب',
    'testimonials.read': 'مقروء',
    'testimonials.testimonial1': "أستخدم HighStream منذ 6 أشهر، لم أواجه مشاكل في التخزين المؤقت أبداً! جودة مثالية 👍",
    'testimonials.testimonial2': "إعداد سريع، فريق دعم رائع. يعمل بشكل مثالي على Samsung TV 📺",
    'testimonials.testimonial3': "أخيراً وجدت IPTV موثوق! جميع القنوات تعمل، بدون انقطاع ⭐",
    'testimonials.testimonial4': "ساعدني الدعم في الإعداد في 5 دقائق. خدمة رائعة! 🔥",
    'testimonials.testimonial5': "أفضل خدمة IPTV جربتها. جودة 4K مذهلة 🎬",

    // Infrastructure content
    'infrastructure.subtitle': 'تقنية على مستوى المؤسسات تشغل ملايين البثوث عالمياً',
    'infrastructure.globalServers': '50+ خادم عالمي',
    'infrastructure.globalServersDesc': 'شبكة خوادم عالمية للأداء الأمثل',
    'infrastructure.globalServersMetric': '99.9% وقت التشغيل',
    'infrastructure.backupTitle': 'نظام النسخ الاحتياطي التلقائي',
    'infrastructure.backupDesc': 'تكرارات متعددة تضمن الخدمة المستمرة',
    'infrastructure.backupMetric': 'صفر وقت توقف',
    'infrastructure.cdnTitle': 'شبكة CDN مضادة للتخزين المؤقت',
    'infrastructure.cdnDesc': 'توصيل ذكي للمحتوى لبث سلس',
    'infrastructure.cdnMetric': '< 1ث وقت التحميل',
    'infrastructure.monitoringTitle': 'مراقبة الشبكة 24/7',
    'infrastructure.monitoringDesc': 'مراقبة فورية وحل فوري للمشاكل',
    'infrastructure.monitoringMetric': 'دعم 24/7',
    'infrastructure.techTitle': 'مدعوم بتقنية متقدمة',
    'infrastructure.globalCdn': 'شبكة CDN عالمية',
    'infrastructure.loadBalancing': 'توزيع الأحمال',
    'infrastructure.autoScaling': 'التوسع التلقائي',
    'infrastructure.analytics': 'تحليلات فورية',

    // Payment content
    'payment.subtitle': 'خيارات دفع متعددة لراحتك وأمانك',
    'payment.eneba': 'Eneba',
    'payment.enebaDesc': 'بطاقات ائتمان وخصم',
    'payment.enebaFeature1': 'دفع فوري',
    'payment.enebaFeature2': 'قبول عالمي',
    'payment.enebaFeature3': 'دفع آمن',
    'payment.wise': 'Wise',
    'payment.wiseDesc': 'تحويل بنكي',
    'payment.wiseFeature1': 'رسوم منخفضة',
    'payment.wiseFeature2': 'متعدد العملات',
    'payment.wiseFeature3': 'تحويل سريع',
    'payment.crypto': 'Crypto',
    'payment.cryptoDesc': 'عملة مشفرة',
    'payment.cryptoFeature1': 'بيتكوين',
    'payment.cryptoFeature2': 'إيثريوم',
    'payment.cryptoFeature3': 'مجهول',
    'payment.howItWorks': 'كيف يعمل',
    'payment.step1Title': 'اشتر عبر Eneba / Wise / Crypto',
    'payment.step1Desc': 'اختر طريقة الدفع المفضلة لديك',
    'payment.step2Title': 'أرسل الإيصال (واتساب / تلغرام)',
    'payment.step2Desc': 'أرسل تأكيد الدفع إلى دعمنا',
    'payment.step3Title': 'احصل على الوصول في أقل من 5 دقائق',
    'payment.step3Desc': 'استلم بيانات تسجيل الدخول فوراً',
    'payment.acceptsCards': 'يقبل جميع بطاقات الائتمان والخصم الرئيسية عالمياً',

    // Pricing content
    'pricing.title': 'اختر خطتك المثالية',
    'pricing.subtitle': 'تشمل جميع الخطط وصولاً كاملاً لميزاتنا المميزة. بدون رسوم مخفية، بدون عقود.',
    'pricing.feature1': '20K+ قناة مباشرة',
    'pricing.feature2': 'أفلام ومسلسلات VOD',
    'pricing.feature3': 'جودة 4K فائقة الوضوح',
    'pricing.feature4': 'دعم جميع الأجهزة',
    'pricing.feature5': 'دعم العملاء 24/7',
    'pricing.feature6': 'شبكة CDN مضادة للتخزين المؤقت',
    'pricing.feature7': 'دعم أولوية',
    'pricing.feature8': 'وصول متعدد الأجهزة',
    'pricing.feature9': 'دعم مميز',
    'pricing.originallyText': 'في الأصل',
    'pricing.paymentInfo': 'معالجة دفع آمنة • تفعيل فوري • دعم 24/7',
    'pricing.creditCards': 'بطاقات ائتمان',
    'pricing.bankTransfer': 'تحويل بنكي',
    'pricing.cryptocurrency': 'عملة مشفرة',

    // Footer content
    'footer.copyright': '© 2024 HighStream. جميع الحقوق محفوظة.',
    'footer.sslSecured': 'SSL محمي',
    'footer.globalCdn': 'شبكة CDN عالمية',
    'footer.product': 'المنتج',
    'footer.company': 'الشركة',

    // FAQ content
    'faq.mainTitle': 'الأسئلة الشائعة (FAQ)',
    'faq.intro': 'مرحباً بك في قسم الأسئلة الشائعة. لقد جمعنا إجابات على الأسئلة الأكثر شيوعاً حول خدمة البث IPTV لدينا لمنحك ثقة كاملة في HighStream. هدفنا هو تزويدك بالمعلومات التي تحتاجها، مما يضمن أن تكون تجربتك سلسة وآمنة قدر الإمكان.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Initialize from localStorage or default to 'en'
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('userLanguage') as Language;
      return savedLanguage && ['en', 'es', 'fr', 'it', 'de', 'ar'].includes(savedLanguage) ? savedLanguage : 'en';
    }
    return 'en';
  });


  const dir = language === 'ar' ? 'rtl' : 'ltr';

   const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('userLanguage', lang);
  };

  return (
   <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t,dir }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

// Hook personnalisé pour utiliser le contexte
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};